/* Application Constants */
sonarQubeUrl='http://34.239.251.172:9000'

node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('build') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install'
       sh 'npm run build'
     }
   }
   
   stage('SonarQube Analysis') {
    // requires SonarQube Scanner 2.8+
    def scannerHome = tool 'SonarScanner';
    withSonarQubeEnv('Sonar') {
      sh "${scannerHome}/bin/sonar-scanner -Dproject.settings=sonar-project.properties"
    }
  }
   
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'GitHub') {
       def app = docker.build("experiencedevops/reactapp:${commit_id}", '.').push()
     }
   }
}
