node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('build') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install'
       sh 'webpack'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'GitHub') {
       def app = docker.build("experiencedevops/reactapp:${commit_id}", '.').push()
     }
   }
}
